name: Release
on: workflow_dispatch

jobs:
  ci:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false # Needed so that semantic release can use the admin token

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: NPM
        uses: ./

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Personal access token with repo permissions
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update tag with latest major version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git tag 'v${{steps.semantic.outputs.new_release_major_version}}' --force
          git push 'https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git' --tags --force
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
