name: Test CI
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: '@ng-easy/npm-setup'
        uses: ./
        with:
          milliseconds: 1000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
